In [1]:
import numpy as np
from scipy import linalg
A = np.array([[1,2],[2,1]])
print(A)
print('-'*20)
print(linalg.inv(A))
# A 的逆矩阵
print('-'*20)
print(A.dot(linalg.inv(A)))
# A 乘 A逆，数据复杂的话，可能对角线外不为0，那是不确定度，近似于0

[[1 2]
 [2 1]]
--------------------
[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]
--------------------
[[1. 0.]
 [0. 1.]]


用矩阵的方式解多元方程

$$x+y+z=0$$
$$x=1$$
$$y=-1$$

系数矩阵为：

$$\left[\begin{matrix}1 & 1 & 1 \cr 1 & 0 & 0 \cr 0 & 1 & 0\end{matrix}\right]$$ 

值矩阵为：

$$\left[\begin{matrix}0 \cr 1 \cr -1\end{matrix}\right]$$ 

计算公式为：

$$\left[\begin{matrix}x \cr y \cr z\end{matrix}\right]=\left[\begin{matrix}1 & 1 & 1 \cr 1 & 0 & 0 \cr 0 & 1 & 0\end{matrix}\right]^{-1} \left[\begin{matrix}0 \cr 1 \cr -1\end{matrix}\right]=\left[\begin{matrix}1 \cr -1 \cr 0\end{matrix}\right]$$ 

In [3]:
import numpy as np
from scipy import linalg
C = np.array([[1,1,1],[1,0,0],[0,1,0]])
# A 的逆矩阵
R = np.array([[0],[1],[-1]])
np.linalg.solve(C, R)

array([[ 1.],
       [-1.],
       [-0.]])

In [4]:
A = np.array([[1,2],[3,4]])
linalg.det(A)
#计算行列式

-2.0

In [5]:
A = np.array([[1, 2], [3, 4]])
la, v = linalg.eig(A)
l1, l2 = la
#计算矩阵的特征值
print(l1, l2)
v1, v2 = v
print(v1,v2)
#计算矩阵的特征向量

(-0.3722813232690143+0j) (5.372281323269014+0j)
[-0.82456484 -0.41597356] [ 0.56576746 -0.90937671]


着实不好意思，之前学得线性代数很多东西都忘了，等我复习后再加回来